include:
  - template: Dependency-Scanning.gitlab-ci.yml

image: node

cache:
  paths:
    - node_modules/

pages:
  script:
    - npm install
    - npm run generate
  artifacts:
    paths:
      - public
  only:
    - master
